### ISSUE TITLE
patch failed

### ISSUE THREAD

**Issue by liugangnhm** [larrupingpig/vimgdb-for-vim7.4#1]
patching file vim74/src/auto/configure
Hunk #1 succeeded at 632 (offset 28 lines).
Hunk #2 succeeded at 807 (offset 30 lines).
Hunk #3 succeeded at 1470 (offset 30 lines).
Hunk #4 succeeded at 7082 (offset 258 lines).
Hunk #5 succeeded at 9462 with fuzz 1 (offset 256 lines).
patching file vim74/src/buffer.c
Hunk #1 FAILED at 672.
Hunk #2 succeeded at 5450 (offset 61 lines).
Hunk #3 succeeded at 5496 (offset 61 lines).
Hunk #4 succeeded at 5518 (offset 61 lines).
Hunk #5 succeeded at 5598 (offset 65 lines).
Hunk #6 succeeded at 5782 (offset 69 lines).
Hunk #7 succeeded at 5824 (offset 69 lines).
1 out of 7 hunks FAILED -- saving rejects to file vim74/src/buffer.c.rej
patching file vim74/src/clewn/gdb.h
patching file vim74/src/clewn/gdb_lvl2.c
patching file vim74/src/clewn/gdb_lvl3.c
patching file vim74/src/clewn/misc.c
patching file vim74/src/clewn/misc.h
patching file vim74/src/clewn/obstack.c
patching file vim74/src/clewn/obstack.h
patching file vim74/src/config.h.in
Hunk #1 succeeded at 426 (offset 1 line).
patching file vim74/src/config.mk.in
patching file vim74/src/configure.in
Hunk #1 succeeded at 1810 (offset 79 lines).
Hunk #2 succeeded at 2734 (offset 79 lines).
patching file vim74/src/eval.c
Hunk #1 succeeded at 546 (offset 11 lines).
Hunk #2 succeeded at 7980 (offset 56 lines).
Hunk #3 succeeded at 11172 (offset 140 lines).
Hunk #4 succeeded at 12530 (offset 258 lines).
patching file vim74/src/ex_cmds.c
Hunk #1 succeeded at 6864 (offset 79 lines).
Hunk #2 succeeded at 6967 (offset 79 lines).
Hunk #3 succeeded at 6975 (offset 79 lines).
Hunk #4 succeeded at 7005 (offset 79 lines).
patching file vim74/src/ex_getln.c
Hunk #1 succeeded at 759 (offset 7 lines).
Hunk #2 succeeded at 6391 (offset 16 lines).
Hunk #3 succeeded at 6460 (offset 16 lines).
Hunk #4 succeeded at 6603 (offset 16 lines).
patching file vim74/src/feature.h
Hunk #1 succeeded at 1280 (offset -10 lines).
patching file vim74/src/gdb.c
patching file vim74/src/globals.h
Hunk #1 succeeded at 1231 (offset 3 lines).
patching file vim74/src/gui.c
patching file vim74/src/gui_gtk_x11.c
Hunk #1 succeeded at 5379 (offset 8 lines).
Hunk #2 succeeded at 5415 (offset 8 lines).
Hunk #3 succeeded at 5453 (offset 8 lines).
Hunk #4 succeeded at 5474 (offset 8 lines).
Hunk #5 succeeded at 5537 (offset 8 lines).
patching file vim74/src/gui_x11.c
patching file vim74/src/main.c
Hunk #2 succeeded at 1432 (offset -4 lines).
patching file vim74/src/Makefile
Hunk #13 succeeded at 571 (offset 1 line).
Hunk #14 succeeded at 859 (offset 4 lines).
Hunk #15 succeeded at 946 (offset 4 lines).
Hunk #16 succeeded at 1497 (offset 6 lines).
Hunk #17 succeeded at 1506 (offset 6 lines).
Hunk #18 succeeded at 1523 (offset 6 lines).
Hunk #19 succeeded at 1590 (offset 8 lines).
Hunk #20 succeeded at 1658 (offset 10 lines).
Hunk #21 succeeded at 1701 (offset 13 lines).
Hunk #22 succeeded at 2781 (offset 32 lines).
Hunk #23 succeeded at 3220 (offset 40 lines).
patching file vim74/src/normal.c
Hunk #1 succeeded at 632 (offset -28 lines).
Hunk #2 succeeded at 726 (offset -34 lines).
Hunk #3 succeeded at 754 (offset -34 lines).
Hunk #4 succeeded at 942 (offset -39 lines).
Hunk #5 succeeded at 1002 (offset -42 lines).
Hunk #6 succeeded at 1118 (offset -39 lines).
Hunk #7 succeeded at 8936 (offset -158 lines).
patching file vim74/src/option.c
Hunk #1 succeeded at 546 (offset 6 lines).
Hunk #2 succeeded at 1260 (offset 24 lines).
patching file vim74/src/option.h
Hunk #1 FAILED at 572.
1 out of 1 hunk FAILED -- saving rejects to file vim74/src/option.h.rej
patching file vim74/src/os_unix.c
Hunk #1 succeeded at 205 (offset 8 lines).
Hunk #2 succeeded at 341 (offset 8 lines).
Hunk #3 succeeded at 394 (offset 8 lines).
Hunk #4 succeeded at 413 (offset 8 lines).
Hunk #5 succeeded at 444 (offset 8 lines).
Hunk #6 succeeded at 474 (offset 8 lines).
Hunk #7 succeeded at 496 (offset 7 lines).
Hunk #8 succeeded at 972 (offset 10 lines).
Hunk #9 succeeded at 1424 (offset 17 lines).
Hunk #10 succeeded at 5325 (offset 138 lines).
Hunk #11 succeeded at 5404 (offset 138 lines).
Hunk #12 succeeded at 5428 (offset 138 lines).
Hunk #13 FAILED at 5597.
Hunk #14 succeeded at 5645 (offset 132 lines).
1 out of 14 hunks FAILED -- saving rejects to file vim74/src/os_unix.c.rej
patching file vim74/src/proto/gdb.pro
patching file vim74/src/proto.h
Hunk #1 succeeded at 261 (offset 2 lines).
patching file vim74/src/screen.c
Hunk #1 succeeded at 6518 (offset 104 lines).
patching file vim74/src/structs.h
Hunk #1 succeeded at 661 (offset 10 lines).
Hunk #2 succeeded at 673 (offset 10 lines).
patching file vim74/src/version.c
Hunk #1 succeeded at 260 (offset 12 lines).
patching file vim74/src/window.c
Hunk #1 succeeded at 6456 (offset 67 lines).

i use vim-7-4-402 from github.

**Comment by cpiger** [comment]
this patch is for version 7.4

**Comment by hlin117** [comment]
Did you get `vim7.4` from mercurial? The one downloadable on the vim website is the one you want.

I originally cloned the repository from mercurial, but also received angry failure messages. After using the one on the vim website, it seems to be going much more smoothly.

With that said, I think it would help in the README.md to specify not to use the one on the mercurial repository.
